---
- hosts: all

  tasks:
   - name: create docker images using war file
     command: docker build -t simple-devops-image:latest .
     args:
        chdir: /opt/docker

   - name: create tag to image
     command: docker tag simple-devops-image vikramrautdocker/simple-devops-image:latest

   - name: push image on to dockerhub
     command: docker push vikramrautdocker/simple-devops-image:latest

   - name: remove the image
     command: docker rmi simple-devops-image:latest vikramrautdocker/simple-devops-image:latest
     ignore_errors: yes 

